### ISSUE TITLE
Twitter has big extra space

### ISSUE THREAD

**Issue by literakl** [editor-js/embed#37]
I have tested with two tweets and there is a big space after the tweet preview
![image](https://user-images.githubusercontent.com/6383287/91075898-0b971400-e63f-11ea-8d70-e9a2c668328b.png)

**Comment by brc-dd** [comment]
I am using custom Twitter config like this:

```js
        twitter: {
          regex: /^https?:\/\/twitter\.com\/(?:#!\/)?(\w+)\/status(?:es)?\/(\d+)(?:\/.*)?$/,
          embedUrl:
            'https://twitframe.com/show?url=https://twitter.com/<%= remote_id %>',
          html: '<iframe class="embed-tool__content--twitter"></iframe>',
          id: ids => ids.join('/status/')
        },
```

And in SCSS I have, 

```scss
@mixin caption {
  margin: 2em auto;
  padding: 0;
  text-align: center;

  &__caption {
    border: 0;
    box-shadow: none;
    color: #757575;
    padding: 0;
    text-align: center;

    &[contentEditable='true'][data-placeholder]:empty::before {
      display: inline !important;
    }

    &[contentEditable='false']:empty {
      display: none;
      visibility: hidden;
    }
  }
}

.embed-tool {
  @include caption;

  &__content {
    background-color: transparent;
    border: 0px solid;

    &--twitter {
      width: 80% !important;
    }
  }
}
```

Now using Twitframe's support for postMessage API and JQuery, 

```js
  const handleTweets = () => {
    $('.embed-tool__content--twitter:not([id])').each(function () {
      const val = $(this).attr('src');
      const _id = `tweet_${val.substr(val.lastIndexOf('/') + 1)}_`;
      const id = _id + $(`iframe[id^=${_id}]`).length;

      setTimeout(() => {
        // eslint-disable-next-line
        this.contentWindow.postMessage(
          { element: id, query: 'height' },
          'https://twitframe.com'
        );
      }, 1000);

      $(this).attr({ id });
    });
  };

  const bindListener = () => {
    $(window).on('message', function (e) {
      const oe = e.originalEvent;
      if (oe.origin !== 'https://twitframe.com') return;

      if (oe.data.height && oe.data.element.match(/^tweet_/))
        $(`#${oe.data.element}`).css(
          'height',
          `${parseInt(oe.data.height, 10) + 30}px`
        );
    });
  };
```

EditorJS Config:

```js
  const editor = new EditorJS({
    // ...
    onReady: () => {
      bindListener();

      // ...
    },
    onChange: () => {
      handleTweets();

      // ...
    },
    // ...
  });
```

This is the rendered output:

![image](https://user-images.githubusercontent.com/40380293/103167137-69867300-484e-11eb-98f6-ab6424826995.png)
